### ISSUE TITLE
[Feature]: 면적 입력 화면과 견적 내기 화면 연결하기

### ISSUE THREAD

**Issue by Minkyeong-Ko** [DeveloperAcademy-POSTECH/MacC-Team-FourFour#50]
### Feature 설명

- [ ] 시공면적 입력 모달과 견적내기 화면을 연결합니다
- [ ] 예상 수량을 계산합니다
- [ ] 예상 가격을 계산합니다
- [ ] 예상 가격과 수량을 화면에 나타냅니다

### Related View(Optional)

- ex. HomeView

### 우선순위

★★★★

### 예상 작업 기간

~ 10/13 (목)

**Comment by cozytk** [comment]
@Minkyeong-Ko 이슈닫을게용~
