### ISSUE TITLE
[FEAT]: 장바구니뷰와 약관동의 뷰 연결

### ISSUE THREAD

**Issue by KimDaeSeong8721** [DeveloperAcademy-POSTECH/MacC-Team-FourFour#68]
### Feature 설명

- 장바구니뷰와 약관동의 뷰 연결 

### 우선순위

★★★★

### 예상 작업 기간

~10.14 (금)

**Comment by cozytk** [comment]
@KimDaeSeong8721 이슈닫을게용~
